name: thesis
channels:
  - opensourceeconomics
  - conda-forge
dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- pip
- estimagic>=0.0.30
- nlopt
- numba
- pip:
      - flake8
      - black
      - pre-commit
