name: Continuous Integration

on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: complie latex
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: vinay0410/tectonic-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tex_path: 'latex/main.tex'
